import streamlit as st

# Title and Header
st.title("GenZ Lingo Decoder 🎧")
st.subheader("Understand what the GenZ is saying!")

# Dictionary with 100+ words
data = {
    "Rizz": "Short for charisma; the ability to attract a romantic partner.",
    "Slay": "To do something exceptionally well or look great.",
    "Delulu": "Delusional; having unrealistic beliefs or fantasies.",
    "Cap": "A lie. 'No Cap' means telling the truth.",
    "Sus": "Suspicious, shady, or questionable.",
    "Aura": "The vibe or energy a person radiates.",
    "Cooked": "To be in a hopeless situation or to have failed.",
    "Bussin": "Used to describe food that tastes extremely good.",
    "Bet": "An expression of agreement or confirmation.",
    "G.O.A.T": "Greatest Of All Time.",
    "Simp": "Someone who does way too much for a person they like.",
    "Mid": "Mediocre or average; not very good.",
    "Stan": "An over-the-top or obsessive fan of a celebrity.",
    "Tea": "Gossip. 'Spill the tea' means tell the gossip.",
    "Flex": "To show off your belongings or accomplishments.",
    "Sheesh": "An expression of being impressed or shocked.",
    "Lowkey": "Secretly or discreetly; keeping it on the down-low.",
    "Highkey": "Openly, honestly, or intensely.",
    "Periodt": "Used at the end of a sentence to emphasize a point.",
    "Rent free": "Thinking about something or someone constantly.",
    "Vibe check": "Assessing the energy or mood of a person or place.",
    "Main character": "Someone who is the center of attention or very confident.",
    "Finna": "Short for 'fixing to'; about to do something.",
    "Ghosting": "Stopping all communication with someone without explanation.",
    "Guap": "A lot of money.",
    "Oof": "An exclamation used when someone is in a cringe or painful situation.",
    "Big Yikes": "Used when something is very embarrassing or cringey.",
    "Noob": "A beginner or someone who is bad at something (often in gaming).",
    "Savage": "Someone who is brutally honest or does something bold.",
    "Clapback": "A clever or sharp response to an insult.",
    "Basic": "Someone who likes mainstream or predictable things.",
    "Cancel Culture": "The practice of withdrawing support for public figures after doing something offensive.",
    "W": "Stands for 'Win'. Used when something good happens.",
    "L": "Stands for 'Loss'. Used when something bad happens.",
    "Sending me": "Something that is extremely funny.",
    "Living my best life": "Being happy and successful without worrying about others.",
    "Facts": "Used to agree with a statement because it's true.",
    "I'm dead": "Used when something is so funny you can't stop laughing.",
    "On fleek": "Perfectly done (often used for eyebrows or makeup).",
    "Thirsty": "Desperate for attention or validation.",
    "Boujee": "High-class, fancy, or luxurious.",
    "Drip": "A cool or trendy sense of style/outfit.",
    "Fam": "Close friends or family.",
    "Gucci": "Good, fine, or cool.",
    "Hypebeast": "Someone obsessed with wearing trendy or expensive clothes.",
    "Left on read": "When someone sees your message but doesn't reply.",
    "Moot": "Short for 'mutual followers' on social media.",
    "Mood": "Something you relate to personally.",
    "POG": "Stands for 'Play Of the Game'; used when something cool happens.",
    "Shook": "Extremely surprised or shocked.",
    "Snatched": "Looking very fit or having a great outfit.",
    "Squad": "Your group of friends.",
    "TFW": "Stands for 'That Feeling When'.",
    "Yeet": "To throw something with force or an exclamation of excitement.",
    "Zaddy": "A stylish, attractive man with swag.",
    "Bae": "Before Anyone Else; usually a partner.",
    "Bestie": "Best friend.",
    "Cringe": "Feeling embarrassed for someone else's awkward actions.",
    "Fire": "Amazing, awesome, or trendy.",
    "Fit": "Short for outfit.",
    "Glow up": "A major transformation for the better.",
    "Hits different": "When something is better than usual or unique.",
    "Karen": "A slang term for an entitled or demanding person.",
    "Lit": "Exciting, amazing, or high energy.",
    "Salty": "Being upset or bitter over something minor.",
    "Soft launch": "Posting a subtle hint about a new relationship on social media.",
    "Vibe": "The emotional atmosphere of a place or person.",
    "Woke": "Being aware of social and political issues.",
    "Extra": "Dramatic or over-the-top behavior.",
    "FomO": "Fear Of Missing Out.",
    "Ick": "A sudden feeling of disgust towards someone you liked.",
    "Main character energy": "Living life like you are the star of the show.",
    "Situationship": "A relationship that is more than friends but not official.",
    "Valid": "Something that is acceptable or understandable.",
    "BOP": "A really good song that you want to dance to.",
    "Understood the assignment": "When someone does something perfectly.",
    "Cheugy": "Something that is out of style or trying too hard.",
    "Go off": "Encouraging someone to speak their mind or do their thing.",
    "Hard launch": "Announcing a relationship with a clear photo on social media.",
    "It's giving": "Used to describe the vibe of something (e.g., 'It's giving 90s').",
    "Purr": "An expression of approval or feeling good.",
    "Ratio": "When a reply to a post gets more likes than the original post.",
    "Touch grass": "Telling someone to go outside because they spend too much time online.",
    "Understandable, have a nice day": "A polite way to end a weird conversation.",
    "Vibe check failed": "When someone's energy doesn't match the group.",
    "We love to see it": "Expressing happiness for someone else's success.",
    "Ghosted": "When someone disappears from your life suddenly.",
    "Hater": "Someone who is jealous or negative.",
    "Iconic": "Something truly memorable or legendary.",
    "Keep it 100": "Be completely honest.",
    "No cap": "Truly, no lie.",
    "On god": "I swear, I'm telling the truth.",
    "Out of pocket": "Doing something extreme or uncalled for.",
    "Pick me": "Someone who tries too hard to get attention from the opposite sex.",
    "Queen": "A term of respect for a woman.",
    "Real one": "A loyal or genuine friend.",
    "Side eye": "A judgmental look.",
    "Snack": "Someone who looks very attractive.",
    "Tea time": "Time for gossip.",
    "Unreal": "Something so good it's hard to believe.",
    "Whole snack": "Someone who looks exceptionally good.",
    "Zero chill": "Doing something very bold or having no calmness."
}

# Search functionality
word = st.selectbox("Select a GenZ word to decode:", list(data.keys()))

if st.button("Decode"):
    st.success(f"**Meaning:** {data[word]}")

# Footer
st.markdown("---")
st.write("Created for GenZ Lingo Project | 2026")
