data = {
    "Rizz": "Short for charisma; the ability to attract a romantic partner.",
    "Slay": "To do something exceptionally well or look great.",
    "Delulu": "Delusional; having unrealistic beliefs or fantasies.",
    "Cap": "A lie. 'No cap' means telling the truth.",
    "Sus": "Suspicious, shady, or questionable.",
    "Aura": "The vibe or energy a person radiates.",
    "Cooked": "To be in a hopeless situation or to have failed.",
    "Bussin": "Used to describe food that tastes extremely good.",
    "Bet": "An expression of agreement or confirmation.",
    "G.o.a.t": "Greatest Of All Time.",
    "Simp": "Someone who does way too much for a person they like.",
    "Mid": "Mediocre or average; not very good.",
    "Stan": "An over-the-top or obsessive fan of a celebrity.",
    "Tea": "Gossip. 'Spill the tea' means tell the gossip.",
    "Flex": "To show off your belongings or accomplishments.",
    "Sheesh": "An expression of being impressed or shocked.",
    "Lowkey": "Secretly or discreetly; keeping it on the down-low.",
    "Highkey": "Openly, honestly, or intensely.",
    "Periodt": "Used at the end of a sentence to emphasize a point.",
    "Rent free": "Thinking about something or someone constantly.",
    "Vibe check": "Assessing the energy or mood of a person or place.",
    "Main character": "Someone who is the center of attention or very confident.",
    "Finna": "Short for 'fixing to'; about to do something.",
    "Ghosting": "Stopping all communication with someone without explanation.",
    "Guap": "A lot of money.",
    "Bread": "Slang for money.",
    "W": "Stands for 'Win'. Used when something good happens.",
    "L": "Stands for 'Loss'. Used when something bad happens.",
    "Caught in 4k": "Catching someone doing something wrong with clear evidence.",
    "Opp": "An opponent or enemy.",
    "Glazing": "Over-praising someone, often to get something from them.",
    "Gyatt": "An exclamation used when seeing someone with a large backside.",
    "Pookie": "A cute nickname for a best friend or partner.",
    "Ship": "To support or want a romantic relationship between two people.",
    "Sneaky link": "Someone you are seeing secretly.",
    "Soft launch": "Posting a small hint about a new relationship on social media.",
    "Valid": "Something that is acceptable, good, or true.",
    "Yeet": "To throw something with force or an exclamation of excitement.",
    "Bop": "A really good song.",
    "Drip": "A cool or trendy outfit or style.",
    "Fire": "Something that is amazing or very cool.",
    "Glow up": "A major transformation in appearance or personality.",
    "Humble brag": "Boasting about something under the guise of being modest.",
    "Ick": "A sudden feeling of disgust towards someone you liked.",
    "Living my best life": "Doing exactly what makes you happy.",
    "Mood": "Something you relate to personally.",
    "On fleek": "Perfectly done, usually referring to eyebrows or makeup.",
    "Pick me": "Someone who tries too hard to get attention from the opposite sex.",
    "Queen": "A term of respect or admiration for a woman.",
    "Salty": "Being upset or bitter about something minor.",
    "Shook": "To be genuinely shocked or surprised.",
    "Snack": "Someone who looks very attractive.",
    "Squad": "Your close group of friends.",
    "Stan": "A combination of 'stalker' and 'fan'.",
    "Thirsty": "Desperate for attention, usually romantic.",
    "Touch grass": "Telling someone to go outside because they spend too much time online.",
    "Understood the assignment": "Doing exactly what was expected and doing it perfectly.",
    "Vibe": "The feeling or atmosphere of a place or person.",
    "Woke": "Being aware of social and political issues.",
    "Zesty": "Someone who is energetic or flamboyant.",
    "Side eye": "A look of judgment or suspicion.",
    "Ratioed": "When a reply to a post gets more likes than the post itself.",
    "Clout": "Influence or fame, especially on social media.",
    "Boujee": "High-class or fancy behavior/lifestyle.",
    "Dead": "Something is so funny you 'died' laughing.",
    "Slapping": "Music that sounds very good.",
    "Fam": "Your closest friends or family.",
    "Facts": "I agree with what you just said.",
    "Glow up": "A transformation for the better.",
    "Hype": "Very excited about something.",
    "It's giving": "It has a certain vibe. e.g., 'It's giving main character vibes'.",
    "Looker": "Someone who is very good looking.",
    "Noob": "A beginner or someone who is bad at a game.",
    "Out pocket": "Someone saying something too wild or inappropriate.",
    "Purr": "An expression of approval (like 'slay').",
    "Savage": "Someone who is bold and doesn't care about consequences.",
    "Simp": "Someone who is overly submissive to their crush.",
    "Tea": "The latest gossip.",
    "Valid": "Something that is good or approved.",
    "Wig snatched": "To be extremely impressed by something.",
    "Yikes": "Used when something is embarrassing or awkward.",
    "Zero chill": "Doing something very bold or having no calmness.",
    "Beige flag": "A trait that isn't good or bad, just a bit boring or weird.",
    "Red flag": "A warning sign in a person's character.",
    "Green flag": "A positive trait in a person's character.",
    "Eras": "Refers to a specific phase in someone's life (e.g., 'In my gym era').",
    "Fanum tax": "Stealing a bit of someone's food (popularized by Kai Cenat).",
    "Hulu and hang": "A more modern version of 'Netflix and chill'.",
    "Mewing": "A tongue exercise to define the jawline; also used to stay quiet.",
    "NPC": "Non-Playable Character; someone who acts in a predictable or boring way.",
    "Ohio": "Used to describe something very weird or cringe.",
    "Sigma": "A lone wolf who is successful and cool; an alpha male vibe.",
    "Skibidi": "A nonsensical word from a viral meme, often means 'bad' or 'cool' depending on context.",
    "What the sigma": "A funny way of saying 'What the heck' or 'What the hell'.",
    "Baby Gronk": "Refers to a young kid being hyped as the next big thing.",
    "Livvy Dunne": "Used as a symbol of peak popularity or rizz.",
    "Mogging": "Looking better than someone else in a physical comparison.",
    "Negative aura": "When someone does something so cringe they lose their 'cool points'.",
    "Chat": "Addressing the audience, as if you are a live streamer (e.g., 'Is this real, chat?').",
}

